"""Generate a small, reproducible enterprise-security knowledge graph.

The data are synthetic. They are not LANL data and must not be presented as
real attack detections. Their purpose is to make the PyKEEN workflow quick to
run on a laptop before replacing the generator with a carefully sampled real
log subset.
"""

from __future__ import annotations

import csv
from pathlib import Path

from rules import apply_rules

Triple = tuple[str, str, str]

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"


def write_tsv(path: Path, triples: list[Triple]) -> None:
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file, delimiter="\t")
        writer.writerows(triples)


def generate_base_triples(number_of_processes: int = 180) -> list[Triple]:
    """Create observed log-like facts for a fictitious enterprise."""
    triples: set[Triple] = set()

    families = [
        "family_powershell",
        "family_remote_desktop",
        "family_downloader",
        "family_credential_dump",
        "family_benign_office",
    ]
    family_to_file_kind = {
        "family_powershell": "file_script",
        "family_remote_desktop": "file_rdp_client",
        "family_downloader": "file_payload",
        "family_credential_dump": "file_sensitive_credential_store",
        "family_benign_office": "file_spreadsheet",
    }

    for index in range(number_of_processes):
        process = f"process_{index:03d}"
        user = f"user_{index % 18:02d}"
        workstation = f"workstation_{index % 12:02d}"
        server = f"server_{(index * 5 + 1) % 8:02d}"
        family = families[index % len(families)]
        file_name = f"{family_to_file_kind[family]}_{index % 15:02d}"

        # Log-like observations represented as a labelled property graph / KG.
        triples.update(
            {
                (user, "authenticates_to", workstation),
                (workstation, "runs", process),
                (process, "executed_by", user),
                (process, "has_family", family),
                (process, "accesses", file_name),
            }
        )

        # Network behaviour. Remote desktop and downloader families are made
        # intentionally more network-facing to create useful relational signal.
        if family in {"family_remote_desktop", "family_downloader"}:
            triples.add((process, "connects_to", server))
        else:
            triples.add((process, "connects_to", workstation))

        # A simple context fact; in real work this might come from an asset DB.
        if server.endswith(("00", "03", "06")):
            triples.add((server, "has_role", "role_high_value_server"))
        else:
            triples.add((server, "has_role", "role_standard_server"))

    return sorted(triples)


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    base_triples = generate_base_triples()
    derived_triples = apply_rules(base_triples)
    all_triples = sorted(set(base_triples).union(derived_triples))

    write_tsv(DATA_DIR / "base_triples.tsv", base_triples)
    write_tsv(DATA_DIR / "derived_rule_triples.tsv", derived_triples)
    write_tsv(DATA_DIR / "all_triples.tsv", all_triples)

    with (DATA_DIR / "README.txt").open("w", encoding="utf-8") as file:
        file.write(
            "Files are generated by src/generate_data.py.\n"
            "base_triples.tsv: observed synthetic log-like facts\n"
            "derived_rule_triples.tsv: rule-created facts with logical provenance\n"
            "all_triples.tsv: union used for the KGE experiment\n"
        )

    print(f"Wrote {len(base_triples):,} observed triples.")
    print(f"Wrote {len(derived_triples):,} rule-derived triples.")
    print(f"Wrote {len(all_triples):,} total triples.")


if __name__ == "__main__":
    main()
